services:
  crypto:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/crypto
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

  fournisseuridentite:
    build:
      context: .
      dockerfile: fournisseurIdentite/Dockerfile
    ports:
      - "5093:80"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5433;Database=crypto;Username=postgres;Password=admin

  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      # POSTGRES_DB: crypto
    ports:
      - "5433:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  postgres_data: