services:
  crypto:
    build:
      context: .
      dockerfile: crypto/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/crypto
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

  fournisseuridentite:
    build:
      context: .
      dockerfile: fournisseuridentite/Dockerfile
    ports:
      - "5093:5092"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_URLS: http://+:5092
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=crypto;Username=postgres;Password=admin

  front-crypto:
    build:
      context: .
      dockerfile: front-crypto/Dockerfile
    ports:
      - "3000:80"
      
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      # POSTGRES_DB: crypto
    ports:
      - "5433:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  postgres_data: