spring.application.name=crypto
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/crypto
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp